import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const abi = (name: string) =>
  JSON.stringify(JSON.parse(readFileSync(resolve(import.meta.dirname, `../artifacts/contracts/${name}.sol/${name}.json`), "utf8")).abi, null, 2);
writeFileSync(
  resolve(import.meta.dirname, "../abi.ts"),
  `// Generated by scripts/export-abi.ts from the compiled artifacts.\nexport const stampRegistryAbi = ${abi("StampRegistry")} as const;\n\nexport const creatorLinksAbi = ${abi("CreatorLinks")} as const;\n`,
);
console.log("wrote abi.ts");
