import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const artifact = JSON.parse(readFileSync(resolve(import.meta.dirname, "../artifacts/contracts/StampRegistry.sol/StampRegistry.json"), "utf8"));
writeFileSync(
  resolve(import.meta.dirname, "../abi.ts"),
  `// Generated by scripts/export-abi.ts from the compiled artifact.\nexport const stampRegistryAbi = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`,
);
console.log("wrote abi.ts");
