// Generated by scripts/export-abi.ts from the compiled artifacts.
export const stampRegistryAbi = [
  {
    "inputs": [],
    "name": "AlreadyStamped",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "BadSignature",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "EmptyRoot",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "TooEarly",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "UnknownStream",
    "type": "error"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "streamId",
        "type": "bytes32"
      },
      {
        "indexed": true,
        "internalType": "uint32",
        "name": "minute",
        "type": "uint32"
      },
      {
        "indexed": false,
        "internalType": "bytes32",
        "name": "root",
        "type": "bytes32"
      }
    ],
    "name": "Stamped",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "streamId",
        "type": "bytes32"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "signer",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "meta",
        "type": "string"
      }
    ],
    "name": "StreamOpened",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "signer",
        "type": "address"
      }
    ],
    "name": "nonces",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "signer",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "nonce",
        "type": "uint256"
      },
      {
        "internalType": "string",
        "name": "meta",
        "type": "string"
      }
    ],
    "name": "openDigest",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "signer",
        "type": "address"
      },
      {
        "internalType": "string",
        "name": "meta",
        "type": "string"
      },
      {
        "internalType": "bytes",
        "name": "sig",
        "type": "bytes"
      }
    ],
    "name": "openStream",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "streamId",
        "type": "bytes32"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "streamId",
        "type": "bytes32"
      },
      {
        "internalType": "uint32",
        "name": "minute",
        "type": "uint32"
      },
      {
        "internalType": "uint8",
        "name": "second",
        "type": "uint8"
      },
      {
        "internalType": "bytes32",
        "name": "audioDigest",
        "type": "bytes32"
      },
      {
        "internalType": "bytes32",
        "name": "pictureFull",
        "type": "bytes32"
      },
      {
        "internalType": "bytes32",
        "name": "pictureCenter",
        "type": "bytes32"
      }
    ],
    "name": "secondLeaf",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "streamId",
        "type": "bytes32"
      },
      {
        "internalType": "uint32",
        "name": "minute",
        "type": "uint32"
      },
      {
        "internalType": "bytes32",
        "name": "root",
        "type": "bytes32"
      },
      {
        "internalType": "bytes",
        "name": "sig",
        "type": "bytes"
      }
    ],
    "name": "stamp",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "streamId",
        "type": "bytes32"
      },
      {
        "internalType": "uint32",
        "name": "minute",
        "type": "uint32"
      },
      {
        "internalType": "bytes32",
        "name": "root",
        "type": "bytes32"
      }
    ],
    "name": "stampDigest",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "streamId",
        "type": "bytes32"
      },
      {
        "internalType": "uint32",
        "name": "minute",
        "type": "uint32"
      }
    ],
    "name": "stamps",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "root",
        "type": "bytes32"
      },
      {
        "internalType": "uint64",
        "name": "at",
        "type": "uint64"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "streamId",
        "type": "bytes32"
      }
    ],
    "name": "streams",
    "outputs": [
      {
        "internalType": "address",
        "name": "signer",
        "type": "address"
      },
      {
        "internalType": "uint64",
        "name": "openedAt",
        "type": "uint64"
      },
      {
        "internalType": "uint32",
        "name": "stamped",
        "type": "uint32"
      },
      {
        "internalType": "string",
        "name": "meta",
        "type": "string"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "streamId",
        "type": "bytes32"
      },
      {
        "internalType": "uint32",
        "name": "minute",
        "type": "uint32"
      },
      {
        "internalType": "uint8",
        "name": "second",
        "type": "uint8"
      },
      {
        "internalType": "bytes32",
        "name": "audioDigest",
        "type": "bytes32"
      },
      {
        "internalType": "bytes32",
        "name": "pictureFull",
        "type": "bytes32"
      },
      {
        "internalType": "bytes32",
        "name": "pictureCenter",
        "type": "bytes32"
      },
      {
        "internalType": "bytes32[]",
        "name": "proof",
        "type": "bytes32[]"
      }
    ],
    "name": "verifySecond",
    "outputs": [
      {
        "internalType": "bool",
        "name": "ok",
        "type": "bool"
      },
      {
        "internalType": "uint64",
        "name": "stampedAt",
        "type": "uint64"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

export const creatorLinksAbi = [
  {
    "inputs": [],
    "name": "BadOwnerSignature",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "BadSignerSignature",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ZeroOwner",
    "type": "error"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "signer",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "owner",
        "type": "address"
      }
    ],
    "name": "Linked",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "signer",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "owner",
        "type": "address"
      },
      {
        "internalType": "bytes",
        "name": "signerSig",
        "type": "bytes"
      },
      {
        "internalType": "bytes",
        "name": "ownerSig",
        "type": "bytes"
      }
    ],
    "name": "link",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "signer",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "owner",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "nonce",
        "type": "uint256"
      }
    ],
    "name": "linkDigest",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "signer",
        "type": "address"
      }
    ],
    "name": "nonces",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "signer",
        "type": "address"
      }
    ],
    "name": "ownerOf",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;
